### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by manshu**

### CODE REVIEW

**Comment by manshu** [comment]
Updated to get views from resoruces/views

**Comment by quant-algo** [comment]
@manshu thank you for great work

**Comment by manshu** [comment]
It's still not changing the actual views. Can you look into the code and see why it's not reading from resources/views ?

**Comment by quant-algo** [comment]
are you sure you have changed the view code in resources ? laravel won't load your file until you change them

**Comment by manshu** [comment]
yes, i did. It's still not working. It's loading views from Vendor folder, instead of resources/view folder.

**Pull request merged**
